#!/usr/bin/env php
<?php declare(strict_types=1);

include_once("vendor/autoload.php");

echo "-------------------------\n";
echo "Yami 0.0.1\n\n";

$console = new Console\Runner();
$console->setAppName('Yami');
$console->setAppVersion('0.0.1');

// Add one or more commands here
$console->registerAll([
    'migrate' => [
        'class' => 'Yami\Console\Migrate',
        'description' => 'Migrate new changes to YAML file'
    ],
    'rollback' => [
        'class' => 'Yami\Console\Rollback',
        'description' => 'Rollback recent changes to YAML file'
    ],
    'create' => [
        'class' => 'Yami\Console\Create',
        'description' => 'Create a migration file'
    ],
    'config' => [
        'class' => 'Yami\Console\Config',
        'description' => 'Create a configuration file'
    ],
    'mask' => [
        'class' => 'Yami\Console\Mask',
        'description' => 'Mask the contents of a YAML file'
    ],
]);

$decorator = new Yami\Console\Decorator(new Console\Args($argv));

// Start your engines...
try {
    $console->run();
} catch(Exception $e) {
    $decorator->write([
        [$e->getMessage(), 'red bold']
    ]) . "\n--------\n\n" . $console->getHelp();
    exit(1);
} catch(Throwable $t) {
    $decorator->write([
        [$t, 'red bold']
    ]) . "\n--------\n\n" . $console->getHelp();
    exit(1);
}

exit(0);